banned-words:
  - gay
  - motherfucker
  - machikni
  - fuck
  - fucking
  - bitch
  - asshole
  - khate
  - pussy
  - puti
  - lado
  - bastard
  - noob
  - bhosadike
  - randi
  - muji
  - chhori
  - chut
  - kando
  - sala
  - harami
  - lund
  - gandu
  - gand
  - chutiya
  - teri
  - bosdika
  - chutiyo
kick-message: "your username contains inappropriate words! Change and try again"
